pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'release'

trigger:
  branches:
    include:
    - master

steps:
- task: DotNetCoreInstaller@0
  inputs:
    version: '3.0.100-alpha1-009640'

- script: dotnet build --configuration $(buildConfiguration) src/Cryptography.sln
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
